# Generated by Django 6.1 on 2026-09-05 12:00

import django.db.models.deletion
import django.db.models.functions.uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('invite_code', models.UUIDField(default=django.db.models.functions.uuid.UUID4, editable=False, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_teams', to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField(choices=[('member', 'Участник'), ('manager', 'Менеджер'), ('admin', 'Администратор')], default='member', max_length=7)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='profiles.profile')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='teams.team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('team', 'profile'), name='unique_team_profile')],
            },
        ),
    ]
