# Generated by Django 6.1 on 2026-08-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('member', 'Участник'), ('manager', 'Менеджер'), ('admin', 'Администратор')], default='member', max_length=7),
        ),
    ]
