# Generated by Django 6.1 on 2026-08-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
        ('teams', '0002_membership_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('member', 'Участник'), ('manager', 'Менеджер'), ('admin', 'Администратор'), ('owner', 'Владелец')], default='member', max_length=7),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('team', 'profile'), name='unique_team_profile'),
        ),
    ]
