# Generated by Django 6.1 on 2026-08-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_membership_role_membership_unique_team_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.TextField(choices=[('member', 'Участник'), ('manager', 'Менеджер'), ('admin', 'Администратор'), ('owner', 'Владелец')], default='member', max_length=7),
        ),
    ]
