# Generated by Django 6.1 on 2026-08-29 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__username'], 'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
