# Generated by Django 6.1 on 2026-09-12 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetup',
            options={'ordering': ['-created_at', '-updated_at']},
        ),
    ]
