# Generated by Django 6.1 on 2026-08-29 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['title', 'due_date']},
        ),
    ]
